kotlin.code.style=official
litellmApiKey=sk-EkPFrEt4sniRnvsLRJQn7Q
llmBaseUrl=https://api.deepseek.com
llmApiKey=
llmModel=deepseek-chat
openaiLikeApiKey=
openaiLikeBaseUrl=https://ws-pzity02qkb8f5fja.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1
openaiLikeModel=deepseek-v4-pro
ktorVersion=3.0.3
openaiVersion=2.20.1
logbackVersion=1.5.18
otelVersion=1.51.0
otelSemconvIncubatingVersion=1.34.0-alpha
koogVersion=0.3.0
org.gradle.java.home=/Users/fedor/Library/Java/JavaVirtualMachines/temurin-23.0.2/Contents/Home
